# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'CborCoseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CborCoseExample

  spm_pkg "IOWalletCBOR", :relative_path => "../../../cbor-ios/"

  target 'CborCoseExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CborCoseExampleUITests' do
    # Pods for testing
  end

end
